---
name: lint and test
on:
  push:
  pull_request:
jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.43
        args: --timeout 5m
  lint-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Helm lint
      shell: bash
      run: |
        helm lint ./helm/kubenurse/
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Print go version
      run: go version
    - name: Run unit tests
      run: go test -cover ./...
